### ISSUE TITLE
PasswordBox使用绑定时不会显示

### ISSUE THREAD

**Issue by TwilightLemon** [OrgEleCho/EleCho.WpfSuite#13]
![75ce4c2c51526eb15b04912021ab535b](https://github.com/user-attachments/assets/34d4ff7d-f7e8-4ef6-8c30-e8bdcea5a4a4)
如图，PasswordBox绑定Password属性时不会显示内容，手动输入时正常

**Comment by SlimeNull** [comment]
fixed
